spring:
   datasource: 
      password: root
      username: root
      url: jdbc:mysql://localhost:3306/store_db?useSSL=false&useTimezone=true&serverTimezone=UTC
   jpa:
       hibernate:
          ddl-auto: update
